development:
  adapter: mysql2
  database: instatrace
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  password: ruby

test:
  adapter: mysql2
  database: instatrace_test
  username: root
  encoding: utf8
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  password: ruby

production:
  adapter: mysql2
  database: instatrace
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  password: mz-sql-123
